// Automatically generated by astro-icon
// 1f48b7d7f7f214178eee5d1794fb42f39a981a622bc1558b113c3c994094dd18

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "github"
		| "linkedin"
		| "scholar"
		| "x";
}